name: AI Autofix and Optimize Python (DeepSeek-R1) - Ollama Lib

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  ai_code_review:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install ollama diff-match-patch

      - name: Run AI Autofix Script (DeepSeek-R1) - Ollama Lib
        run: python .github/workflows/ai_autofix_script.py
        env:
          OLLAMA_MODEL: "deepseek-r1:32b"
        timeout-minutes: 30

      - name: Display Patch Output
        if: always() # Always run to show patch even if script fails
        run: |
          echo "--- AI Patch Output (Review Carefully) ---"
          cat ai_patch_output.txt || echo "No patch output generated or script error occurred."
          echo "--- End Patch Output ---"

      - name: Upload Processing Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-autofix-logs
          path: |
            ai_patch_output.txt
            *.log
          compression-level: 6  # Default compression level
          retention-days: 5     # Keep logs for 5 days

      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto-fix: Applied AI suggested changes" || echo "No changes to commit"
          git push